name: 🚀 Build and Deploy to Root

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'assets/**'
      - 'index.html'
      - '.github/workflows/deploy-to-root.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: ⚡ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🏗️ Build
      run: npm run build
      env:
        VITE_SUPABASE_PROJECT_ID: ${{ secrets.VITE_SUPABASE_PROJECT_ID }}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        
    - name: 📂 Copy built files to root
      run: |
        cp dist/index.html .
        cp -r dist/assets .
        rm -rf dist
        
    - name: 📝 Commit built files
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add index.html assets/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🚀 Auto-deploy built files to root [skip ci]"
          git push
        fi
